import SignInForm from "./SignInForm";
export const metadata = {
  title: "Hireloop - Sign In",
  description: "Generated by create next app",
};
export default function SignInPage() {
  return (
    <div
      className="relative mt-10 min-h-screen w-full flex items-center justify-center overflow-hidden"
      style={{ background: "#06060e" }}
    >
      {/* Purple glow top */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute top-0 left-1/2 -translate-x-1/2"
        style={{
          width: "700px",
          height: "320px",
          background:
            "radial-gradient(ellipse 55% 70% at 50% -10%, rgba(110,30,200,0.48) 0%, transparent 75%)",
          zIndex: 1,
        }}
      />

      {/* Bottom fade */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute bottom-0 left-0 right-0"
        style={{
          height: "200px",
          background: "linear-gradient(to top, #06060e 0%, transparent 100%)",
          zIndex: 3,
        }}
      />

      {/* Stars */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage:
            "radial-gradient(circle, rgba(200,190,255,0.5) 1px, transparent 1px)," +
            "radial-gradient(circle, rgba(200,190,255,0.25) 1px, transparent 1px)",
          backgroundSize: "130px 130px, 75px 75px",
          backgroundPosition: "0 0, 38px 38px",
          maskImage:
            "linear-gradient(to bottom, rgba(0,0,0,0.6) 0%, transparent 60%)",
          WebkitMaskImage:
            "linear-gradient(to bottom, rgba(0,0,0,0.6) 0%, transparent 60%)",
          zIndex: 1,
        }}
      />

      {/* Login Card */}
      <div
        className="relative w-full max-w-105 mx-5 mt-20 mb-20"
        style={{ zIndex: 10 }}
      >
        {/* Card glow */}
        <div
          aria-hidden="true"
          className="absolute inset-0 rounded-3xl pointer-events-none"
          style={{
            boxShadow:
              "0 0 80px 0 rgba(100,60,220,0.18), 0 0 0 1px rgba(255,255,255,0.07)",
            borderRadius: "24px",
          }}
        />

        <div
          className="relative rounded-3xl p-8"
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.09)",
            backdropFilter: "blur(24px)",
            WebkitBackdropFilter: "blur(24px)",
          }}
        >
          {/* Logo / Brand */}
          <div className="flex flex-col items-center mb-8">
            <h1
              className="text-white font-bold mb-1"
              style={{
                fontSize: "22px",
                fontFamily: "'Sora','Inter',sans-serif",
                letterSpacing: "-0.02em",
              }}
            >
              Welcome back
            </h1>
            <p
              style={{
                fontSize: "13px",
                color: "rgba(255,255,255,0.4)",
                fontFamily: "'Sora',sans-serif",
              }}
            >
              Sign in to your Hireloop account
            </p>
          </div>

          <div className="flex flex-col gap-5">

            {/* Sign In Form */}
            <SignInForm />
            {/* Sign In Form */}

            {/* Divider */}
            <div className="flex items-center gap-3">
              <div
                className="flex-1 h-px"
                style={{ background: "rgba(255,255,255,0.08)" }}
              />
              <span
                className="text-xs"
                style={{
                  color: "rgba(255,255,255,0.25)",
                  fontFamily: "'Sora',sans-serif",
                }}
              >
                or continue with
              </span>
              <div
                className="flex-1 h-px"
                style={{ background: "rgba(255,255,255,0.08)" }}
              />
            </div>

            {/* Google OAuth */}
            <button
              type="button"
              className="w-full flex items-center justify-center gap-2.5 py-2.5 rounded-xl text-sm font-medium transition-all hover:opacity-90 active:scale-[0.98]"
              style={{
                background: "rgba(255,255,255,0.06)",
                border: "1px solid rgba(255,255,255,0.10)",
                color: "rgba(255,255,255,0.75)",
                fontFamily: "'Sora',sans-serif",
                height: "44px",
                cursor: "pointer",
              }}
            >
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                aria-hidden="true"
              >
                <path
                  d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                  fill="#4285F4"
                />
                <path
                  d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                  fill="#34A853"
                />
                <path
                  d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                  fill="#FBBC05"
                />
                <path
                  d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                  fill="#EA4335"
                />
              </svg>
              Continue with Google
            </button>
          </div>

          {/* Sign Up Link */}
          <p
            className="text-center mt-6 text-xs"
            style={{
              color: "rgba(255,255,255,0.35)",
              fontFamily: "'Sora',sans-serif",
            }}
          >
            Don&apos;t have an account?{" "}
            <a
              href="#"
              style={{ color: "#a78bfa", textDecoration: "none" }}
           
            >
              Sign up for free
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
