import Link from "next/link";
import SignUpForm from "./SignUpForm";
export const metadata = {
  title: "Hireloop - Sign Up",
  description: "Generated by create next app",
};
export default function SignUpPage() {
  return (
    <div
      className="relative mt-10 min-h-screen w-full flex items-center justify-center overflow-hidden"
      style={{ background: "#06060e" }}
    >
      {/* Purple glow top */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute top-0 left-1/2 -translate-x-1/2"
        style={{
          width: "700px",
          height: "320px",
          background:
            "radial-gradient(ellipse 55% 70% at 50% -10%, rgba(110,30,200,0.48) 0%, transparent 75%)",
          zIndex: 1,
        }}
      />

      {/* Globe image bottom center */}

      {/* Bottom fade */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute bottom-0 left-0 right-0"
        style={{
          height: "200px",
          background: "linear-gradient(to top, #06060e 0%, transparent 100%)",
          zIndex: 3,
        }}
      />

      {/* Stars */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-0"
        style={{
          backgroundImage:
            "radial-gradient(circle, rgba(200,190,255,0.5) 1px, transparent 1px)," +
            "radial-gradient(circle, rgba(200,190,255,0.25) 1px, transparent 1px)",
          backgroundSize: "130px 130px, 75px 75px",
          backgroundPosition: "0 0, 38px 38px",
          maskImage:
            "linear-gradient(to bottom, rgba(0,0,0,0.6) 0%, transparent 60%)",
          WebkitMaskImage:
            "linear-gradient(to bottom, rgba(0,0,0,0.6) 0%, transparent 60%)",
          zIndex: 1,
        }}
      />

      {/* Card */}
      <div
        className="relative w-full max-w-105 mx-5 mt-20 mb-20"
        style={{ zIndex: 10 }}
      >
        {/* Card glow */}
        <div
          aria-hidden="true"
          className="absolute inset-0 rounded-3xl pointer-events-none"
          style={{
            boxShadow:
              "0 0 80px 0 rgba(100,60,220,0.18), 0 0 0 1px rgba(255,255,255,0.07)",
            borderRadius: "24px",
          }}
        />

        <div
          className="relative rounded-3xl p-8"
          style={{
            background: "rgba(255,255,255,0.04)",
            border: "1px solid rgba(255,255,255,0.09)",
            backdropFilter: "blur(24px)",
            WebkitBackdropFilter: "blur(24px)",
          }}
        >
          {/* Logo / Brand */}
          <div className="flex flex-col items-center mb-8">
            <h1
              className="text-white font-bold mb-1"
              style={{
                fontSize: "22px",
                fontFamily: "'Sora','Inter',sans-serif",
                letterSpacing: "-0.02em",
              }}
            >
              Create your account
            </h1>
            <p
              style={{
                fontSize: "13px",
                color: "rgba(255,255,255,0.4)",
                fontFamily: "'Sora',sans-serif",
              }}
            >
              Create an account to continue your journey with us.
            </p>
          </div>

          <div className="flex flex-col gap-5">
          {/* Form */}
           <SignUpForm />
           

           

            {/* Google OAuth */}
           
          </div>

         
        </div>
      </div>
    </div>
  );
}
